export POSTGRESS_USERNAME=jacksonudagram;
export POSTGRESS_PASSWORD=jacksonudagram;
export POSTGRESS_DB=jacksonudagram;
export POSTGRESS_HOST=ImageFilterStarterCode-env.uksi6gu6ws.us-east-2.elasticbeanstalk.com 
export AWS_REGION=us-east-2;
export AWS_PROFILE=default;
export AWS_BUCKET=jacksonudagram;
export JWT_SECRET=helloworld;
apiHost=localhost:8080
